const mongoose = require('mongoose');

/**
 * UserPlan — a 7-day personalised study plan generated for a user.
 * Generated by the match engine (content-based filtering + cosine similarity).
 */
const dayItemSchema = new mongoose.Schema(
  {
    dayIndex: { type: Number, min: 0, max: 6, required: true }, // 0 = Mon … 6 = Sun
    lessonId: { type: mongoose.Schema.Types.ObjectId, ref: 'Lesson', default: null },
    topicId: { type: mongoose.Schema.Types.ObjectId, ref: 'Topic', default: null },
    
    // New fields for flexible content types:
    itemId: { type: mongoose.Schema.Types.ObjectId, default: null }, // can be reading ID, writing ID, etc.
    itemType: { type: String, default: 'topic' }, // e.g. 'topic', 'reading', 'speaking', 'writing', 'vocabulary', 'story'
    
    skill: { type: String, default: '' }, // primary skill of this slot
    similarityScore: { type: Number, default: 0 }, // cosine score at generation time
    isExploration: { type: Boolean, default: false }, // was this injected for variety?
    status: {
      type: String,
      enum: ['pending', 'in_progress', 'completed', 'skipped'],
      default: 'pending',
    },
    completedAt: { type: Date, default: null },
  },
  { _id: false }
);

const userPlanSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    weekStart: {
      type: Date,
      required: true, // Monday of the week this plan covers
    },
    weekEnd: {
      type: Date,
      required: true,
    },
    dayItems: [dayItemSchema],
    // The user embedding vector used to generate this plan (for traceability)
    sourceEmbeddingHash: { type: String, default: '' },
    // Level at the time of generation
    generatedForLevel: { type: String, default: '' },
    // Exploration ratio used
    explorationRatio: { type: Number, default: 0.15 },
    // Status of the whole plan
    status: {
      type: String,
      enum: ['active', 'completed', 'expired', 'replaced'],
      default: 'active',
    },
    // Metadata
    generationMethod: { type: String, default: 'content_based_filtering' },
    metadata: { type: mongoose.Schema.Types.Mixed, default: {} },
  },
  {
    timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' },
  }
);

// At most one active plan per user
userPlanSchema.index({ userId: 1, status: 1 });

module.exports = mongoose.model('UserPlan', userPlanSchema);
